// Auto-generated by scripts/generate_photolab_manifest.py
// Do not edit manually unless you do not plan to regenerate it.

window.PHOTOLAB = {
  "digital": [
    {
      "filename": "digital-caucasus-mountain.png",
      "device": "iPhone 17 Pro",
      "location": "Kazbegi, Georgia",
      "description": "Autumn mountains and snow-covered peaks.",
      "date": "2025-08"
    },
    {
      "filename": "digital-flower-hill.png",
      "device": "Fujifilm X100VI",
      "location": "Biei, Hokkaido",
      "description": "Rolling flower hills with a lone pink tree.",
      "date": "2025-08"
    },
    {
      "filename": "digital-forest-wetland.png",
      "device": "Fujifilm X100VI",
      "location": "Pacific Northwest",
      "description": "Quiet green wetland under a dense forest canopy.",
      "date": "2025-08"
    },
    {
      "filename": "digital-sandbar-lagoon.png",
      "device": "DJI Mini 4 Pro",
      "location": "Lake Michigan",
      "description": "Aerial view of shallow water, sandbars, and wind texture.",
      "date": "2025-08"
    }
  ],
  "film": [
    {
      "filename": "film-aerial-forest.png",
      "device": "Olympus 35RC",
      "film": "Kodak Portra 400",
      "location": "Northwoods",
      "description": "Top-down forest textures and a narrow stream.",
      "date": "2025-08"
    },
    {
      "filename": "film-flower-meadow.png",
      "device": "Rollei 35S",
      "film": "Kodak Ektar 100",
      "location": "Furano, Hokkaido",
      "description": "Open meadow with a small cluster of trees.",
      "date": "2025-08"
    },
    {
      "filename": "film-glass-garden.png",
      "device": "Rollei 35S",
      "film": "Fujifilm Pro 400H",
      "location": "Indoor garden",
      "description": "Soft light through glass, water, grass, and stairs.",
      "date": "2025-08"
    }
  ]
};
