// Auto-generated by scripts/generate_photolab_manifest.py
// Do not edit manually unless you do not plan to regenerate it.

window.PHOTOLAB = {
  "digital": [
    {
      "filename": "acadia1.jpeg",
      "device": "X100VI",
      "location": "Bar Harbor, Maine",
      "description": "Acadia National Park autumn coastline",
      "date": "2025-11"
    },
    {
      "filename": "acadia2.jpeg",
      "device": "X100VI",
      "location": "Bar Harbor, Maine",
      "description": "Pier over water at Acadia National Park",
      "date": "2025-11"
    },
    {
      "filename": "biscayne.jpg",
      "device": "iPhone 17 Pro",
      "location": "Miami, FL",
      "description": "Biscayne National Park coastline",
      "date": "2026-04"
    },
    {
      "filename": "lake_powell.jpeg",
      "device": "iPhone 17 Pro",
      "location": "Page, Arizona",
      "description": "Lake Powell marina and desert cliffs",
      "date": "2026-01"
    },
    {
      "filename": "lower_antelope_canyon.jpg",
      "device": "X100VI",
      "location": "Navajo Nation, AZ",
      "description": "Lower Antelope Canyon",
      "date": "2026-01"
    }
  ],
  "film": [
    {
      "filename": "centralpark.jpeg",
      "device": "Rollei 35S",
      "film": "Kodak Ektachrome E100",
      "location": "New York, NY",
      "description": "Cherry blossoms at Central Park.",
      "date": "2026-04"
    },
    {
      "filename": "dc1.jpg",
      "device": "Rollei 35S",
      "film": "Kodak Ektachrome E100",
      "location": "Washington, D.C.",
      "description": "Jefferson Memorial across the Tidal Basin.",
      "date": "2026-04"
    },
    {
      "filename": "dc2.jpg",
      "device": "Rollei 35S",
      "film": "Kodak Ektachrome E100",
      "location": "Washington, D.C.",
      "description": "Washington Monument across the Tidal Basin.",
      "date": "2026-04"
    },
    {
      "filename": "everglades1.jpg",
      "device": "Rollei 35S",
      "film": "Kodak Ektachrome E100",
      "location": "Miami, FL",
      "description": "Shark Valley Observation Tower in Everglades National Park.",
      "date": "2026-04"
    },
    {
      "filename": "everglades2.jpg",
      "device": "Rollei 35S",
      "film": "Kodak Ektachrome E100",
      "location": "Miami, FL",
      "description": "Lily-covered wetland in Everglades National Park.",
      "date": "2026-04"
    },
    {
      "filename": "flowers1.JPG",
      "device": "Olympus 35 RC",
      "film": "Kodak Ektachrome E100",
      "location": "New York, NY",
      "description": "Pink roses blooming against lush foliage near Stuyvesant Town-Peter Cooper Village.",
      "date": "2026-05"
    },
    {
      "filename": "flowers2.JPG",
      "device": "Olympus 35 RC",
      "film": "Kodak Ektachrome E100",
      "location": "New York, NY",
      "description": "Clustered white flowers on a green bush along the Hudson River Waterfront Greenway.",
      "date": "2026-05"
    },
    {
      "filename": "nyc1.JPG",
      "device": "Olympus 35 RC",
      "film": "Kodak Ektachrome E100",
      "location": "New York, NY",
      "description": "The Con Edison powerplant and an E 13th St sign beneath a partly cloudy sky.",
      "date": "2026-05"
    }
  ]
};
