#!/usr/bin/env python3
"""
Generate photography/photos.js from:
  photography/digital/
  photography/digital/photos.csv
  photography/film/
  photography/film/photos.csv

Usage from the site root:
  python scripts/generate_photolab_manifest.py

This lets you add images to the folders, optionally update CSV metadata,
then regenerate one static JS file that works on:
  - Cloudflare Pages
  - GitHub Pages / github.io
  - local file previews
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PHOTO_ROOT = ROOT / "photography"
SUPPORTED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif"}


def read_metadata(csv_path: Path) -> dict[str, dict[str, str]]:
    if not csv_path.exists():
        return {}

    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = csv.DictReader(f)
        metadata = {}
        for row in rows:
            filename = (row.get("filename") or "").strip()
            if filename:
                metadata[filename] = {k: (v or "").strip() for k, v in row.items()}
        return metadata


def scan_gallery(folder_name: str, fields: list[str]) -> list[dict[str, str]]:
    folder = PHOTO_ROOT / folder_name
    folder.mkdir(parents=True, exist_ok=True)

    metadata = read_metadata(folder / "photos.csv")
    images = sorted(
        p for p in folder.iterdir()
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTENSIONS
    )

    items: list[dict[str, str]] = []
    for image in images:
        row = metadata.get(image.name, {})
        item = {"filename": image.name}
        for field in fields:
            item[field] = row.get(field, "")
        items.append(item)

    # Also include CSV rows whose image file has not been added yet.
    # These appear as broken images, which helps catch filename mismatches.
    existing = {item["filename"] for item in items}
    for filename, row in metadata.items():
        if filename not in existing:
            item = {"filename": filename}
            for field in fields:
                item[field] = row.get(field, "")
            items.append(item)

    return items


def main() -> None:
    digital = scan_gallery("digital", ["device", "location", "description", "date"])
    film = scan_gallery("film", ["device", "film", "location", "description", "date"])

    manifest = "window.PHOTOLAB = " + json.dumps(
        {"digital": digital, "film": film},
        ensure_ascii=False,
        indent=2,
    ) + ";\n"

    out = PHOTO_ROOT / "photos.js"
    out.write_text(
        "// Auto-generated by scripts/generate_photolab_manifest.py\n"
        "// Do not edit manually unless you do not plan to regenerate it.\n\n"
        + manifest,
        encoding="utf-8",
    )

    print(f"Wrote {out.relative_to(ROOT)}")
    print(f"Digital photos: {len(digital)}")
    print(f"Film photos: {len(film)}")


if __name__ == "__main__":
    main()
